### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by QwertRvg** [Wulian233/Chat-Impressive-Animation#6]
The mod is not working for me
Thought it was because of Beautified Chat or Chat Heads at first, but even after disabling still doesn't work
Here is the latest.log if that helps:

[latest.log](https://github.com/user-attachments/files/16841700/latest.log)

**Comment by Wulian233** [comment]
Thank you for your feedback! I noticed that your modloader is Forge, and as far as we know, Forge does not support sending chat animation, only opening chat animation. Unfortunately, my co-author @TexBlock and I don't know how to solve this bug🙁

https://github.com/Wulian233/Chat-Impressive-Animation?tab=readme-ov-file#-features

Can you see the animation of opening the chat, or is the white bar on the left (which the mod removed) visible to you?

**Comment by QwertRvg** [comment]
Hi!
So the chat opening animation does play but the white line does still appear.

**Comment by Wulian233** [comment]
According to your description only part of the mod is working properly

In previous tests forge was able to remove the message indicator, and a full functional demo should look like this https://modrinth.com/mod/chat-impressive-animation/gallery

**Comment by QwertRvg** [comment]
yeah that sadly was not the case for me
